{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path | default (print "/" .Release.Name "/" .Chart.Name "/") }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-service
            port:
              number: {{ .Values.ports.nginx.targetPort }}
{{ end }}
