# Name of the image tu pull from registry
image: acrarolibotnonprod.azurecr.io/3d-nginx:v1.0.0-rc-profile

ingress:
  enabled: false

  path: "/nginx-for-s3/"
  host: "*" # "minikube.local"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

route:
  enabled: true

  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"

deployment:
  pod:
    annotations:
      co.elastic.logs/enabled: 'true'
      co.elastic.logs/module: 'nginx'
      co.elastic.logs/fileset.stdout: 'access'
      co.elastic.logs/fileset.stderr: 'error'
      co.elastic.metrics/module: 'nginx'
      co.elastic.metrics/metricsets: 'stubstatus'
      co.elastic.metrics/hosts: '${data.host}:8080/nginx_status'
      co.elastic.metrics/period: '10s'

s3:
  host: "10.8.1.13"
  port: "9000"
  accessId: "raster"
  secretKey: "rasterPassword"

ports:
  # s3: 9000
  opa: 9191
  envoy: 8000

authentication:
  opa:
    enabled: false
    customHeaderName: 'x-api-key'

envoy:
  image: envoyproxy/envoy
  imageTag: v1.18.3
  maxRequestBytes: 8192

environment: development
# cloudProvider is provider where you are going to deploy map exporter, it could be: aws, minikube
cloudProvider: azure