static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Values.ports.envoy }}
    filter_chains:
    - filters:
      - name: envoy.filters.http.health_check
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.health_check.v2.HealthCheck
          pass_through_mode: true
          headers:
            - name: ":path"
              exact_match: "/healthcheck"
      - name: envoy.router
        typed_config: {}
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service
          http_filters:
          - name: envoy.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              transport_api_version: V3
              with_request_body:
                max_request_bytes: 8192
                allow_partial_message: true
              failure_mode_allow: false
              grpc_service:
                google_grpc:
                  target_uri: localhost:{{ .Values.ports.opa }}
                  stat_prefix: ext_authz
                timeout: 0.5s
          - name: envoy.filters.http.router
  clusters:
  - name: service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: {{ .Values.ports.deployment }}
    common_lb_config:
      healthy_panic_threshold:
        value: 0
    health_checks:
      - timeout: 1s
        interval: 2s
        unhealthy_threshold: 3
        healthy_threshold: 1
        always_log_health_check_failures: true
        event_log_path: /tmp/health-check.log
        http_health_check:
          path: /healthcheck
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      envoy:
        resource_limits:
          listeners:
            example_listener_name:
              connection_limit: 10000
      overload:
        global_downstream_max_connections: 50000
